AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  NotifierFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 120
      Handler: app.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          CATEGORIES_TABLE: suo-categories
          FROM_EMAIL: <your-email-address>
          POSTS_TABLE: suo-aws-posts
          SNS_TOPIC_ARN: ''
          USERS_TABLE: aws-suo-users
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Action:
                - dynamodb:GetItem
                - dynamodb:DeleteItem
                - dynamodb:PutItem
                - dynamodb:Scan
                - dynamodb:Query
                - dynamodb:UpdateItem
                - dynamodb:BatchWriteItem
                - dynamodb:BatchGetItem
                - dynamodb:DescribeTable
                - dynamodb:ConditionCheckItem
              Resource:
                - arn:aws:dynamodb:<your-region>:<your-account-id>:table/suo-aws-posts
                - arn:aws:dynamodb:<your-region>:<your-account-id>:table/suo-aws-posts/index/*
              Effect: Allow
            - Action:
                - dynamodb:GetItem
                - dynamodb:DeleteItem
                - dynamodb:PutItem
                - dynamodb:Scan
                - dynamodb:Query
                - dynamodb:UpdateItem
                - dynamodb:BatchWriteItem
                - dynamodb:BatchGetItem
                - dynamodb:DescribeTable
                - dynamodb:ConditionCheckItem
              Resource:
                - arn:aws:dynamodb:<your-region>:<your-account-id>:table/suo-categories
                - arn:aws:dynamodb:<your-region>:<your-account-id>:table/suo-categories/index/*
              Effect: Allow
            - Action:
                - dynamodb:GetItem
                - dynamodb:DeleteItem
                - dynamodb:PutItem
                - dynamodb:Scan
                - dynamodb:Query
                - dynamodb:UpdateItem
                - dynamodb:BatchWriteItem
                - dynamodb:BatchGetItem
                - dynamodb:DescribeTable
                - dynamodb:ConditionCheckItem
              Resource:
                - arn:aws:dynamodb:<your-region>:<your-account-id>:table/aws-suo-users
                - arn:aws:dynamodb:<your-region>:<your-account-id>:table/aws-suo-users/index/*
              Effect: Allow
            - Action:
                - sns:Publish
              Resource: 'arn:aws:sns:<your-region>:<your-account-id>:'
              Effect: Allow
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
      RecursiveLoop: Terminate
      SnapStart:
        ApplyOn: None
      Tags:
        lambda:createdBy: SAM
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto